language: android
jdk: oraclejdk7

# Use the Travis Container-Based Infrastructure
sudo: false

env:
  global:
    # Initiating clean Gradle output (clean the log first when you rebuild)
    - TERM=dumb
    # Amount of memory granted to Gradle JVM
    # should avoid the randomly failing test starts for App:test (exit code 137)
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    # increase timout should avoid ShellCommandUnresponsiveException but looks like value hasn't any effect
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    # The encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
    - secure: "cZvhAS5aQleOOk65Zuz58IEWYAfB7ptx6Mkf1n31Q/Fs3u+qPOA6GIwEFvtKNcHIclAQe8aDZl6fwyRpl/90lPIkgoXCI6A/YV7zMJhXBQOm7Rhe5IPoA+UkwV8Oz4wA/TBhu6qkOqUxDVvL3S+MYAKPVmxHAoCzkGKUAtjEuKk="

android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-m2repository

cache:
  directories:
    # Caching depemdencies for faster builds
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  # Emulator Management: Create, Start
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &

script:
  # Execute Unit Tests
  - ./gradlew App:test -s
  
  # don't know why but waiting at this position reduce randomly failing test starts 
  # for App:test (exit code 137) and App:connectedCheck (ShellCommandUnresponsiveException)
  - ./android-wait-for-emulator
  
  - ./gradlew Core:test
  - ./gradlew Database:test

  # Execute Component Tests
  - ./gradlew AppCT:test
  
  # Execute Tests on Emulator
  - ./gradlew App:connectedCheck

  # Create coverage report
  - ./gradlew jacocoTestReport

  # Check lint hints
  - ./gradlew lint

after_success:
  # Only report code coverage if all tasks are successful
  - ./gradlew coveralls
  
addons:
  coverity_scan:
    project:
      name: "nenick/QuAcc"
      description: "Build submitted via Travis CI"
    branch_pattern: master
