language: android
jdk: oraclejdk7

# Use the Travis Container-Based Infrastructure
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-m2repository

cache:
  directories:
    # Caching depemdencies for faster builds
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  # Emulator Management: Create, Start
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./android-wait-for-emulator

script:
  # Execute Unit Tests
  - travis_fold:start:AppUnitTests && ./gradlew App:test && travis_fold:end:AppUnitTests
  - ./gradlew Core:test
  - ./gradlew Database:test

  # Execute Component Tests
  - ./gradlew AppCT:test
  
  # Execute Tests on Emulator
  - ./gradlew App:connectedCheck

  # Create coverage report
  - ./gradlew jacocoTestReport

  # Check lint hints
  - ./gradlew lint

after_script:
  # Report code coverage
  - ./gradlew coveralls
