sudo: false
language: android
jdk: oraclejdk7

android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-m2repository

cache:
  directories:
    # caching depemdencies for faster builds
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

install:
  # install custom novoda plugin version
  - wget https://raw.githubusercontent.com/nenick/android-gradle-template/master/Scripts/install-custom-gradle-test-plugin.sh -P Scripts
  - wget https://raw.githubusercontent.com/nenick/android-gradle-template/master/Scripts/novoda-deploy.gradle -P Scripts
  - chmod +x Scripts/install-custom-gradle-test-plugin.sh
  - Scripts/install-custom-gradle-test-plugin.sh

script:
  # Execute Unit and Component Test
  - ./gradlew test
  
  # Execute Tests on Emulator
  - ./gradlew connectedAndroidTest
